### ISSUE TITLE
refactor `Validator` definition to match with `Result`

### ISSUE THREAD

**Issue by kyasu1** [arowM/elm-form-validator#2]
How about rearrange arguments of `Validator a err` to `Validator err a` like `Result error value`?

使っていて気になったのですが、 `type Validator a err`の定義を`type Result error value`に合わせたほうが使いやすいかなと思いました。

他のパッケージでも大体エラーが先になっているので、0.19にバンプする際に合わせてはいかがなと。

**Comment by arowM** [comment]
Though apparently `Validator` and `Result` is similar, but actually they have totally different meanings.
Also, it is natural to put target of `map` function last of data type.
e.g., `map : (a -> b) -> Foo x y z w a -> Foo x y z w b`
It has no sense to map value itself to validate, so I believe the order of arguments should be left as it is.

ご提案ありがとうございます！💕

実はこれは意図的に今の引数順にしています。
`Result err val` の場合は「 `err` または `val` をとる」という意味ですが、 `Validator err val` の場合は 「`val` 型の値に対するチェックをして `err` を返す」という意味であり、実は意味論的には別物です。

また `map` 関数を持つデータ型は、一般的には型引数の最後の値を `map` 対象にします。
(e.g., `map : (a -> b) -> Foo x y z w a -> Foo x y z w b` )
`Validator val err` の `val` に対して `map` を定義するのは意味的に不自然になため、 `err` を最後の引数にしています。

**Comment by arowM** [comment]
Feel free to reopen if you have any thoughts against it.

もし「その主張はなんだかおかしい」とか「伝えたい意図がちゃんと伝わってない」とかあれば、お気軽に Reopen してください m(_ _)m

**Comment by kyasu1** [comment]
After trying some other validation packages I was convinced myself that `Validator` should behave like `Result`. But this package was designed differently. Thank you for clarifying.

詳細ありがとうございます。私の理解不足でした。

**Comment by arowM** [comment]
Suggestions from who actually uses this library is super helpful.

いえいえ〜 実際に使っていただいた上でご提案いただけてとても助かります。
また、わざわざ英語にしていただいてありがとうございます！
（勝手に英語も付記させていただきましたが、日本語でコメントしていただいても全然OKです）
